version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    env_file:
      - ../server/.env
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
